decomposition: 'kronecker'
detach_head: False
model_name: 'meta-llama/Llama-2-13b-hf'
tmp_path: 'path/llama2-13b-k-12'
layer_numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]
q_proj:
    r: 1
    m1: 2
    n1: 1
k_proj:
    r: 1
    m1: 2
    n1: 1
v_proj:
    r: 1
    m1: 1
    n1: 1
o_proj:
    r: 1
    m1: 1
    n1: 2
gate_proj:
    r: 1
    m1: 2
    n1: 1
up_proj:
    r: 1
    m1: 2
    n1: 1
down_proj:
    r: 1
    m1: 1
    n1: 2
lm_head:
    r: 1
    m1: 5120
    n1: 32000
embed_tokens:
    r: 1
    m1: 32000
    n1: 5120
not_replace_layers: 

