decomposition: 'kronecker'
model_name: 'facebook/opt-13b'
tmp_path: 'path/opt-13b-k'
layer_numbers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41]
q_proj:
    r: 3
    m1: 4
    n1: 1
k_proj:
    r: 3
    m1: 4
    n1: 1
v_proj:
    r: 1
    m1: 1
    n1: 1
out_proj:
    r: 3
    m1: 1
    n1: 4
fc1:
    r: 3
    m1: 4
    n1: 1
fc2:
    r: 3
    m1: 1
    n1: 4
lm_head:
    r: 3
    m1: 1280
    n1: 50272
embed_tokens:
    r: 3
    m1: 50272
    n1: 1280
embed_positions: 
    r: 3
    m1: 2050
    n1: 1280
not_replace_layers: 
